using System.Runtime.InteropServices;

namespace OpenChat.Core.Marmot;

/// <summary>
/// P/Invoke bindings for the Marmot native library.
/// These will be auto-generated by csbindgen when the Rust library is built.
/// </summary>
internal static partial class MarmotInterop
{
    private const string LibraryName = "openchat_native";

    [LibraryImport(LibraryName, EntryPoint = "marmot_create_client")]
    internal static partial IntPtr CreateClient(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string privateKeyHex,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string publicKeyHex);

    [LibraryImport(LibraryName, EntryPoint = "marmot_destroy_client")]
    internal static partial void DestroyClient(IntPtr client);

    [LibraryImport(LibraryName, EntryPoint = "marmot_generate_key_package")]
    internal static partial IntPtr GenerateKeyPackage(
        IntPtr client,
        out int dataLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_create_group")]
    internal static partial IntPtr CreateGroup(
        IntPtr client,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string groupName,
        out int groupIdLength,
        out ulong epoch);

    [LibraryImport(LibraryName, EntryPoint = "marmot_add_member")]
    internal static partial IntPtr AddMember(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        IntPtr keyPackageData,
        int keyPackageLength,
        out int welcomeLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_process_welcome")]
    internal static partial IntPtr ProcessWelcome(
        IntPtr client,
        IntPtr welcomeData,
        int welcomeLength,
        out int groupIdLength,
        out ulong epoch,
        out IntPtr groupName,
        out IntPtr membersJson);

    [LibraryImport(LibraryName, EntryPoint = "marmot_encrypt_message")]
    internal static partial IntPtr EncryptMessage(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string plaintext,
        out int ciphertextLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_decrypt_message")]
    internal static partial IntPtr DecryptMessage(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        IntPtr ciphertext,
        int ciphertextLength,
        out IntPtr senderPublicKey,
        out ulong epoch);

    [LibraryImport(LibraryName, EntryPoint = "marmot_process_commit")]
    internal static partial int ProcessCommit(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        IntPtr commitData,
        int commitLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_update_keys")]
    internal static partial IntPtr UpdateKeys(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        out int commitLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_remove_member")]
    internal static partial IntPtr RemoveMember(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string memberPublicKey,
        out int commitLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_get_group_info")]
    internal static partial int GetGroupInfo(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        out IntPtr groupName,
        out ulong epoch,
        out IntPtr membersJson);

    [LibraryImport(LibraryName, EntryPoint = "marmot_export_group_state")]
    internal static partial IntPtr ExportGroupState(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        out int stateLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_import_group_state")]
    internal static partial int ImportGroupState(
        IntPtr client,
        IntPtr groupId,
        int groupIdLength,
        IntPtr state,
        int stateLength);

    [LibraryImport(LibraryName, EntryPoint = "marmot_free_buffer")]
    internal static partial void FreeBuffer(IntPtr buffer);

    [LibraryImport(LibraryName, EntryPoint = "marmot_free_string")]
    internal static partial void FreeString(IntPtr str);

    [LibraryImport(LibraryName, EntryPoint = "marmot_get_last_error")]
    internal static partial IntPtr GetLastError();
}
